import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
    title: "I18_Languages",
    description: "Generated by create next app",
};

export default function LocaleLayout({
    children,
    params: { locale },
}: {
    children: React.ReactNode;
    params: { locale: string };
}) {
    return (
        <html lang={locale}>
            <body className="flex flex-col  max-w-4xl min-h-screen  mx-auto gap-10">
            <Header />
              {children}
            <Footer />
              </body>
        </html>
    );
}
